document.getElementById("testdiv").onmousemove = function(evt) {
  document.getElementById("altKey").textContent = evt.altKey;
  document.getElementById("button").textContent = evt.button;
  document.getElementById("buttons").textContent = evt.buttons;
  document.getElementById("clientX").textContent = evt.clientX;
  document.getElementById("clientY").textContent = evt.clientY;
  document.getElementById("ctrlKey").textContent = evt.ctrlKey;
  document.getElementById("metaKey").textContent = evt.metaKey;
  document.getElementById("movementX").textContent = evt.movementX;
  document.getElementById("movementY").textContent = evt.movementY;
  document.getElementById("offsetX").textContent = evt.offsetX;
  document.getElementById("offsetY").textContent = evt.offsetY;
  document.getElementById("pageX").textContent = evt.pageX;
  document.getElementById("pageY").textContent = evt.pageY;
  document.getElementById("region").textContent = evt.region;
  document.getElementById("relatedTarget").textContent = evt.relatedTarget;
  document.getElementById("screenX").textContent = evt.screenX;
  document.getElementById("screenY").textContent = evt.screenY;
  document.getElementById("shiftKey").textContent = evt.shiftKey;
  document.getElementById("x").textContent = evt.x;
  document.getElementById("y").textContent = evt.y;
}